apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volcano
  namespace: prod-lepton
spec:
  releaseName: volcano
  targetNamespace: kube-system
  interval: 10m
  # 关键点 1: 允许在安装失败时进行补救
  install:
    remediation:
      retries: 3
    # 关键点 2: 允许接管已存在的资源（非常重要）
    disableWait: false
  upgrade:
    force: true # 如果版本不同，强制覆盖
    cleanupOnFail: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: volcano
      version: "1.11.0"
      sourceRef:
        kind: HelmRepository
        name: volcano-oci
        namespace: prod-lepton